FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine3.14 AS builder

WORKDIR /src/
COPY . .
RUN dotnet restore 
RUN dotnet publish -c Release --nologo -o publish/linux -r linux-x64 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

#Build runtime image
FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine3.14
RUN apk add --no-cache gcompat 
WORKDIR /app
COPY --from=builder /src/publish/linux/api .
COPY appsettings.json .
EXPOSE 5500
ENTRYPOINT ["/app/api"]