FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS builder

WORKDIR /src/
COPY . .
RUN dotnet restore 
RUN dotnet publish -c Release --nologo -o publish/linux -r linux-x64 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

#Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:8.0-jammy-amd64

WORKDIR /app
COPY --from=builder /src/publish/linux/api .
COPY appsettings.json .
EXPOSE 5501
ENTRYPOINT ["/app/api"]
